name: mdenv
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37_1000
  - atomicwrites=1.3.0=py37_1
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py37_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=h6de7cb9_1003
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h46ab8bc_1002
  - gitdb2=2.0.5=py37_0
  - gitpython=3.0.2=py_0
  - glib=2.58.3=h9d45998_1002
  - icu=64.2=h6de7cb9_1
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython
  - seaborn
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.13.2=py37_0
  - jpeg=9c=h1de35cc_1001
  - jsonschema=3.1.1=py37_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py37_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.5.0=py_0
  - kiwisolver=1.1.0=py37h0a44026_0
  - libclang=8.0.1=h770b8ee_1
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=h01d97ff_1005
  - libllvm8=8.0.1=h770b8ee_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.17=h01d97ff_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37h54f8f79_0
  - mistune=0.8.4=py37h1de35cc_1000
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.14=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - more-itertools=7.2.0=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.1=py37_0
  - nspr=4.20=h0a44026_1000
  - nss=3.46=h39b4b1f_0
  - numpy=1.16.4=py37hacdab7b_0
  - numpy-base=1.16.4=py37h6575580_0
  - openssl=1.1.1c=h01d97ff_0
  - packaging=19.2=py_0
  - pandas=0.24.2=py37h0a44026_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - pcre=8.41=h0a44026_1003
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.3.1=py37_0
  - pluggy=0.13.0=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - ptyprocess=0.6.0=py_1001
  - py=1.8.0=py37_0
  - pygments=2.4.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.12.3=py37h2a560b1_0
  - pyrsistent=0.15.5=py37h0b31af3_0
  - pytest=4.6.2=py37_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.0=py37hee98d25_0
  - qt=5.12.5=h1b46049_0
  - qtconsole=4.5.5=py_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.21.3=py37h27c97d8_0
  - scipy=1.3.1=py37h1410ff5_0
  - send2trash=1.5.0=py_0
  - setuptools=41.4.0=py37_0
  - six=1.12.0=py37_0
  - smmap2=2.0.5=py37_0
  - sqlite=3.30.1=ha441bb4_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py37h1de35cc_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - seglearn==1.0.9

